name: Agent-Linux-CI

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          
        
  build_docker_images:
    runs-on: ubuntu-latest
    needs: build 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3        
        
      - name: Build local Docker images via docker-compose
        run: |
          docker compose -f docker-compose.yml build
      - name: Tag and Push Images to Docker Hub
        env:
          DOCKER_REPO: ${{ secrets.DOCKERHUB_USERNAME }} 
          TAG_SHA: ${{ github.sha }}
          PROJECT_NAME: linux-agent 
        run: |
          BACKEND_LOCAL_NAME="${PROJECT_NAME}-backend"
          FRONTEND_LOCAL_NAME="${PROJECT_NAME}-frontend"
          
          docker tag ${BACKEND_LOCAL_NAME}:latest $DOCKER_REPO/linux-agent-backend:$TAG_SHA
          docker tag ${BACKEND_LOCAL_NAME}:latest $DOCKER_REPO/linux-agent-backend:latest
          docker push $DOCKER_REPO/linux-agent-backend:$TAG_SHA
          docker push $DOCKER_REPO/linux-agent-backend:latest
          
          # Tagging and Pushing Frontend
          docker tag ${FRONTEND_LOCAL_NAME}:latest $DOCKER_REPO/linux-agent-frontend:$TAG_SHA
          docker tag ${FRONTEND_LOCAL_NAME}:latest $DOCKER_REPO/linux-agent-frontend:latest
          docker push $DOCKER_REPO/linux-agent-frontend:$TAG_SHA
          docker push $DOCKER_REPO/linux-agent-frontend:latest

          

